import React, { useEffect, useState } from 'react';
import { motion } from 'motion/react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../context/AuthContext';
import { Wallet, ArrowUpRight, ArrowDownLeft, Download, Plus, DollarSign, Calendar, Loader2, FileText } from 'lucide-react';
import { cn } from '../lib/utils';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

import { useSettings } from '../context/SettingsContext';

const Contributions: React.FC = () => {
  const { user, profile } = useAuth();
  const { appSettings } = useSettings();
  const currency = appSettings?.currency || 'Ksh';
  const [contributions, setContributions] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [showAddModal, setShowAddModal] = useState(false);
  const [amount, setAmount] = useState('');
  const [type, setType] = useState<'subscription' | 'one-time' | 'grant'>('one-time');

  const fetchContributions = async () => {
    try {
      const { data, error } = await supabase
        .from('contributions')
        .select('*, profiles(name)')
        .order('date', { ascending: false });
      
      if (error) throw error;
      setContributions(data || []);
    } catch (err) {
      console.error('Error fetching contributions:', err);
    } finally {
      setLoading(false);
    }
  };

  const generatePDF = () => {
    const doc = new jsPDF();
    const timestamp = new Date().toLocaleString();
    
    // Header
    doc.setFillColor(16, 185, 129); // Emerald-500
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('PROGRESS HUB YETU', 15, 25);
    
    doc.setFontSize(10);
    doc.text('OFFICIAL SAVINGS STATEMENT', 15, 32);
    
    // Audit Info
    doc.setTextColor(150, 150, 150);
    doc.setFontSize(8);
    doc.text(`Printed: ${timestamp}`, 145, 20);
    doc.text(`Generated By: ${profile?.name || profile?.email || 'Authorized System'}`, 145, 25);
    
    // Table
    const tableData = contributions.map(c => [
      c.date,
      c.profiles?.name || 'Unknown',
      c.type.toUpperCase(),
      c.status.toUpperCase(),
      `$${Number(c.amount).toFixed(2)}`
    ]);

    autoTable(doc, {
      startY: 50,
      head: [['Date', 'Personnel', 'Type', 'Status', 'Amount']],
      body: tableData,
      theme: 'striped',
      headStyles: { fillColor: [16, 185, 129], textColor: [255, 255, 255] },
      styles: { fontSize: 8, cellPadding: 5 },
    });

    // Summary
    const finalY = (doc as any).lastAutoTable.finalY + 20;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text(`Total Verified Savings: $${totalVerified.toLocaleString()}.00`, 15, finalY);
    doc.text(`Total Pending Records: $${pendingAmount.toLocaleString()}.00`, 15, finalY + 7);
    
    doc.save(`Hub_Yetu_Statement_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  useEffect(() => {
    fetchContributions();
  }, []);

  const handleAddContribution = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user || !amount) return;

    try {
      const { error } = await supabase
        .from('contributions')
        .insert({
          profile_id: user.id,
          amount: parseFloat(amount),
          type,
          status: 'pending'
        });

      if (error) throw error;

      // Log activity
      await supabase.from('activities').insert({
        profile_id: user.id,
        type: 'contribution',
        content: `Initiated a ${type} contribution of $${amount}`
      });

      setAmount('');
      setShowAddModal(false);
      fetchContributions();
    } catch (err) {
      console.error('Error adding contribution:', err);
    }
  };

  const totalVerified = contributions
    .filter(c => c.status === 'verified')
    .reduce((sum, c) => sum + Number(c.amount), 0);

  const pendingAmount = contributions
    .filter(c => c.status === 'pending')
    .reduce((sum, c) => sum + Number(c.amount), 0);

  return (
    <div className="p-4 md:p-10 space-y-10 max-w-7xl mx-auto w-full">
      <header className="flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div>
          <h2 className="text-4xl font-black tracking-tighter text-black dark:text-white uppercase">
            Group <span className="text-gray-300 dark:text-gray-600">Savings</span>
          </h2>
          <p className="mt-2 text-gray-400 font-medium italic">Tracking member contributions and fund flow</p>
        </div>
        <div className="flex gap-4">
           <button 
             onClick={generatePDF}
             className="flex items-center gap-3 px-6 py-4 glass dark:bg-white/5 rounded-2xl text-[10px] font-black uppercase tracking-[0.2em] transition-all active:scale-95"
           >
             <FileText className="w-5 h-5 text-gray-400" />
             Report
           </button>
           <button 
             onClick={() => setShowAddModal(true)}
             className="flex items-center gap-3 px-8 py-4 bg-emerald-500 text-white rounded-2xl text-[10px] font-black uppercase tracking-[0.2em] shadow-xl hover:shadow-[0_10px_20px_rgba(16,185,129,0.3)] transition-all active:scale-95"
           >
             <Plus className="w-5 h-5" />
             Log Deposit
           </button>
        </div>
      </header>

      {/* Stats Card */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
         <div className="lg:col-span-2 bg-black dark:bg-white p-10 rounded-[2.5rem] text-white dark:text-black relative overflow-hidden">
            <p className="text-[10px] font-black uppercase tracking-[0.2em] opacity-40 mb-4">Total Hub Value</p>
            <h3 className="text-6xl font-black tracking-tighter mb-10">{currency} {totalVerified.toLocaleString()}<span className="text-xl opacity-40 italic">.00</span></h3>
            <div className="flex items-center gap-10">
               <div>
                  <p className="text-[9px] font-black uppercase tracking-widest opacity-40 mb-1">Weekly Growth</p>
                  <div className="flex items-center gap-2 text-emerald-400 font-bold">
                     <ArrowUpRight className="w-4 h-4" />
                     <span>+0.0%</span>
                  </div>
               </div>
            </div>
         </div>

         <div className="bg-gray-50 dark:bg-gray-900 border border-gray-100 dark:border-gray-800 p-8 rounded-[2.5rem] flex flex-col justify-between relative overflow-hidden">
            <div>
               <div className="w-12 h-12 bg-white dark:bg-black rounded-2xl flex items-center justify-center mb-6 shadow-sm">
                  <ArrowUpRight className="w-6 h-6 text-emerald-500" />
               </div>
               <p className="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-1">Pending Deposits</p>
               <h4 className="text-3xl font-black tracking-tight dark:text-white">{currency} {pendingAmount.toLocaleString()}</h4>
            </div>
            <p className="text-[10px] font-medium text-gray-400 mt-4 italic">Verification in progress</p>
         </div>
      </div>

      {/* Transaction List */}
      <div className="bg-white dark:bg-[#111111] rounded-[2.5rem] border border-gray-100 dark:border-gray-800 overflow-hidden shadow-sm">
         <div className="p-8 border-b border-gray-50 dark:border-gray-900 flex items-center justify-between">
            <h3 className="text-sm font-black uppercase tracking-[0.2em] dark:text-white flex items-center gap-3">
               <Wallet className="w-5 h-5" />
               Transaction Ledger
            </h3>
         </div>

         <div className="divide-y divide-gray-50 dark:divide-gray-900 text-left">
            {loading ? (
              <div className="p-20 flex justify-center"><Loader2 className="animate-spin text-gray-300" /></div>
            ) : contributions.length > 0 ? contributions.map((tx, i) => (
               <motion.div 
                 key={tx.id}
                 initial={{ opacity: 0, x: -10 }}
                 animate={{ opacity: 1, x: 0 }}
                 transition={{ delay: i * 0.1 }}
                 className="p-8 hover:bg-gray-50/50 dark:hover:bg-white/5 transition-all group flex flex-col md:flex-row md:items-center justify-between gap-6"
               >
                  <div className="flex items-center gap-6">
                     <div className="w-12 h-12 bg-gray-100 dark:bg-gray-900 rounded-2xl flex items-center justify-center text-gray-400 font-black">
                        {tx.type === 'subscription' ? <span className="text-blue-500">S</span> : tx.type === 'grant' ? <span className="text-emerald-500">G</span> : <span className="text-orange-500">O</span>}
                     </div>
                     <div>
                        <h4 className="font-bold text-sm dark:text-white uppercase tracking-tight">{tx.profiles?.name}</h4>
                        <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">{tx.type} • {tx.date}</p>
                     </div>
                  </div>

                  <div className="flex items-center gap-8 justify-between md:justify-end">
                     <div className="text-right">
                        <p className="text-lg font-black tracking-tight text-emerald-500">+{currency} {Number(tx.amount).toLocaleString()}</p>
                        <div className="flex items-center justify-end gap-1.5">
                           <div className={cn("w-1.5 h-1.5 rounded-full", tx.status === 'verified' ? "bg-emerald-500" : "bg-orange-500 animate-pulse")}></div>
                           <span className="text-[9px] font-bold text-gray-400 uppercase tracking-widest">{tx.status}</span>
                        </div>
                     </div>
                  </div>
               </motion.div>
            )) : (
              <div className="p-20 text-center text-gray-400 font-medium">No transactions on record.</div>
            )}
         </div>
      </div>

      {/* Add Modal */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-6 bg-black/60 backdrop-blur-sm">
          <motion.div 
            initial={{ scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="w-full max-w-md bg-white dark:bg-[#111111] rounded-[2.5rem] p-10 shadow-2xl space-y-8"
          >
            <h3 className="text-2xl font-black uppercase tracking-tight dark:text-white">Deposit Resources</h3>
            <form onSubmit={handleAddContribution} className="space-y-6">
              <div className="space-y-2">
                <label className="text-[10px] font-black uppercase tracking-widest text-gray-400 ml-4">Amount ({currency})</label>
                <input 
                  type="number" 
                  value={amount}
                  onChange={(e) => setAmount(e.target.value)}
                  placeholder="0.00"
                  className="w-full bg-gray-50 dark:bg-gray-900 border-none rounded-2xl px-6 py-4 text-lg font-black dark:text-white outline-none focus:ring-2 ring-emerald-500/20 transition-all"
                  required
                />
              </div>
              <div className="space-y-2">
                <label className="text-[10px] font-black uppercase tracking-widest text-gray-400 ml-4">Deposit Type</label>
                <select 
                  value={type}
                  onChange={(e) => setType(e.target.value as any)}
                  className="w-full bg-gray-50 dark:bg-gray-900 border-none rounded-2xl px-6 py-4 text-sm font-bold dark:text-white outline-none focus:ring-2 ring-emerald-500/20 transition-all"
                >
                  <option value="one-time">One-time Support</option>
                  <option value="subscription">Monthly Subscription</option>
                  <option value="grant">Organization Grant</option>
                </select>
              </div>
              <div className="flex gap-4 pt-4">
                <button 
                  type="button"
                  onClick={() => setShowAddModal(false)}
                  className="flex-1 py-4 text-[10px] font-black uppercase tracking-widest text-gray-400 hover:text-black dark:hover:text-white transition-all"
                >
                  Cancel
                </button>
                <button 
                  type="submit"
                  className="flex-1 py-4 bg-emerald-500 text-white rounded-2xl text-[10px] font-black uppercase tracking-widest shadow-xl hover:shadow-emerald-500/20 transition-all active:scale-95"
                >
                  Log Deposit
                </button>
              </div>
            </form>
          </motion.div>
        </div>
      )}
    </div>
  );
};

export default Contributions;
